; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = adafruit_metro_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed =  2000000
board_build.filesystem = littlefs
board_build.partitions = 16MB.csv
monitor_filters = esp32_exception_decoder
build_type = debug
build_flags = 
	-DBOARD_HAS_PSRAM
	-DLWIP_WND_SCALE=0
	-DTCP_RCV_SCALE=7
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = 
	spi
	fs
	spiffs
	lennarthennigs/Button2@^2.2.4
	bitbank2/AnimatedGIF@^2.1.0
	bitbank2/JPEGDEC@^1.4.2
	khoih-prog/AsyncTCP_SSL@>=1.3.1
	khoih-prog/AsyncHTTPRequest_Generic@>=1.12.0
	khoih-prog/AsyncHTTPSRequest_Generic@>=2.5.0
	moononournation/GFX Library for Arduino@^1.5.6
